# Generated by Django 5.0.3 on 2024-04-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='haplotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosaicID', models.CharField(max_length=255)),
                ('geneID', models.CharField(max_length=255)),
                ('geneType', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('Sequence', models.TextField()),
            ],
        ),
    ]
