# Generated by Django 5.0.3 on 2024-04-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchDatabase', '0001_initial'),
    ]

    operations = [
    ]
