# Generated by Django 5.0.3 on 2024-04-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchDatabase', '0002_auto_20240403_1148'),
    ]

    operations = [
    ]
