# Generated by Django 5.0.3 on 2024-04-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchDatabase', '0003_auto_20240403_1156'),
    ]

    operations = [
    ]
