# Generated by Django 5.0.3 on 2024-04-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchDatabase', '0004_auto_20240403_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haplotype',
            options={'managed': False},
        ),
    ]
