# Generated by Django 5.0.3 on 2024-04-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchDatabase', '0005_alter_haplotype_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='haplotype',
            table='haplotype',
        ),
    ]
