# Generated by Django 5.0.3 on 2024-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchDatabase', '0007_snp'),
    ]

    operations = [
        migrations.CreateModel(
            name='transcript',
            fields=[
                ('mosaicID', models.CharField(max_length=255)),
                ('geneID', models.CharField(max_length=255)),
                ('transcriptID', models.CharField(max_length=255)),
                ('transcriptIndex', models.CharField(max_length=255)),
                ('isExon', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('length', models.IntegerField()),
                ('transcriptRange', models.CharField(max_length=255)),
                ('transcriptLength', models.IntegerField()),
                ('proteinSequence', models.TextField()),
                ('nucleotideSequence', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'transcript',
                'managed': False,
            },
        ),
    ]
