# Generated by Django 5.0.3 on 2024-04-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchDatabase', '0010_genetpm_mosaictpm_transcripttpm_xenologoustpm'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gt42genomeid',
            table='gt42_genome_id',
        ),
    ]
