# Generated by Django 5.0.3 on 2024-05-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchDatabase', '0012_gt42nextid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GT42MosaicNetworkEdges',
            fields=[
                ('source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('color', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gt42_mosaic_network_edges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GT42MosaicNetworkNodes',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('symbolSize', models.DecimalField(decimal_places=4, max_digits=10)),
                ('color', models.CharField(max_length=255)),
                ('totalDegree', models.IntegerField()),
                ('inDegree', models.IntegerField()),
                ('outDegree', models.IntegerField()),
                ('adjacency', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gt42_mosaic_network_nodes',
                'managed': False,
            },
        ),
    ]
