# Generated by Django 5.0.3 on 2024-05-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchDatabase', '0013_gt42mosaicnetworkedges_gt42mosaicnetworknodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GT42GeneNetworkEdges',
            fields=[
                ('source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('color', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gt42_gene_network_edges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GT42GeneNetworkNodes',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('symbolSize', models.DecimalField(decimal_places=4, max_digits=10)),
                ('color', models.CharField(max_length=255)),
                ('totalDegree', models.IntegerField()),
                ('inDegree', models.IntegerField()),
                ('outDegree', models.IntegerField()),
                ('adjacency', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gt42_gene_network_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GT42XenologousNetworkEdges',
            fields=[
                ('source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('color', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gt42_xenologous_network_edges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GT42XenologousNetworkNodes',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('symbolSize', models.DecimalField(decimal_places=4, max_digits=10)),
                ('color', models.CharField(max_length=255)),
                ('totalDegree', models.IntegerField()),
                ('inDegree', models.IntegerField()),
                ('outDegree', models.IntegerField()),
                ('adjacency', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gt42_xenologous_network_nodes',
                'managed': False,
            },
        ),
    ]
